# 需要定时运行的目录，映射到 /jobby/code 中
services:
    neo4j:
        image: neo4j:4.1
        user: "neo4j:neo4j"
        container_name: neo4j
        ports:
            - "7474:7474"
            - "7687:7687"
        restart: always
        volumes:
            - ./data:/data
            - ./conf:/var/lib/neo4j/conf
            - ./csv:/var/lib/neo4j/import
        environment:
            - NEO4J_AUTH=none
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
